require 'active_support'
require 'active_support/core_ext/hash'

require 'dovico/version'
require 'dovico/api_client'
require 'dovico/app'
require 'dovico/config_parser'
require 'dovico/model/assignment'
require 'dovico/model/time_entry_generator'
require 'dovico/model/employee'
require 'dovico/model/project'
require 'dovico/model/task'
require 'dovico/model/time_entry'
